local ProfileType = require(script.ProfileType)
local ProfileActionType = require(script.ProfileActionType)
local JanitorType = require(script.JanitorType)
local WeaponConfigType = require(script.WeaponConfigType)

export type ProfileType = ProfileType.ProfileType
export type ProfileActionType = ProfileActionType.ProfileActionType
export type JanitorType = JanitorType.JanitorType
export type WeaponConfigType = WeaponConfigType.WeaponConfigType

return {}
